# Generated by Django 5.2.6 on 2025-09-15 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('result', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation_id', models.CharField(max_length=360)),
                ('message_type', models.CharField(default='Text', max_length=50)),
                ('generated_image_b64', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
    ]
