# Generated by Django 5.2.6 on 2025-09-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='conversation_id',
            new_name='conversation_name',
        ),
    ]
